apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-frontend
  namespace: pfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfe-frontend
  template:
    metadata:
      labels:
        app: pfe-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/dhouhaka/pfe-frontend:12958c42ba496eaaaa7d60c0ce5749ef2241960f
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pfe-frontend-config
